### ISSUE TITLE
Option to edit column format

### ISSUE THREAD

**Issue by sonn-gamm** [youngcut/kirby-column-blocks#1]
hi! great work.

preamble: i know one can work around the limitation described in the title by making a new block with a different column composition and drag and drop the blocks from the previous block column.

but, is the option to edit the current block column intentional? eg too complex to implement? or simply not necessary in your experience?

anyway, many thanks!

**Comment by plain-solutions-gmbh** [comment]
Hi. Thanks. It's a plesure. 
I can't understand your matter. Could you please be more specific?

**Comment by plain-solutions-gmbh** [comment]
I think i know what you mean. You want to customize the column block globaly. I'm just added the solution to the description.
