### ISSUE TITLE
"Row-Template" with predefined block types

### ISSUE THREAD

**Issue by teichsta** [youngcut/kirby-column-blocks#2]
Hi @youngcut and thanks for this great plugin,

is it possible to provide "custom columsets" with predefined blocks?

What i'd like to achieve is use this columns block to "simulate" a small gallery or kind of "row templates" like 1/3 + 2/3 with small text and a big image block predefined already to reduce clicks for the user if that makes sense to you.

I am wondering if that is possible and i would achieve that with your plugin.

Thanks in advance, Thomas E.-E.

**Comment by plain-solutions-gmbh** [comment]
Hi Thomas
As i understood right, you want a column block with a specific setting (1/3 - 2/3) with abbelity to add only a set of blocks. These could be done easly by adding this to your blueprint:

````
fields:
  myblock:
    label: Block content
    type: blocks
    fieldsets:
      - heading
      - text
      columns:
        extends: blocks/columns
        fields:
          layout:
            layouts:
              - "1/3, 2/3"
            fieldsets:
              - image
              - text

**Comment by teichsta** [comment]
Hi Roman,

thanks for your reply!

No, not quite. The columns should already be filled with a given set of blocks. For a "gallery" i'd like to prepare a gallery-3x1-column with 3 columns and 3 image blocks already filled in.

**Comment by plain-solutions-gmbh** [comment]
I think, this can be achieved by using the [default property](https://getkirby.com/docs/reference/panel/fields/blocks#default-values). But these are more questions about block fields in general. Please ask further questions to the [Kirby Forum](https://forum.getkirby.com/).
