### ISSUE TITLE
Closing div Tag in Column Snippet

### ISSUE THREAD

**Issue by jonasholfeld** [youngcut/kirby-column-blocks#3]
There is a spare closing div tag in the column snippet (/kirby-column-blocks-main/snippets/blocks/columns.php on line 19). It destroys your html if you don't delete it manuallly.

Otherwise, great plugin!!

**Comment by plain-solutions-gmbh** [comment]
Thanks. It's fixed in [Version 1.0.1](https://github.com/youngcut/kirby-column-blocks/releases/tag/1.0.1)
