### ISSUE TITLE
Kirby 4 compatibility + enhancement suggestion

### ISSUE THREAD

**Issue by LaurentTacco** [youngcut/kirby-column-blocks#6]
In the Kirby 4 panel, the native layout field doesn't show any dialog when adding a new row if a single layout option is defined in the blueprint.

For a better user experience and overall consistency, it would be great if this Column plugin could behave the same way, so when a new block is added, if "1/2 1/2" is the only available layout option for example, then the dialog is skipped and you can directly fill the two columns.

And well, it would be great to have an official update for Kirby 4 instead of having to tweak the panel CSS in order to make it work 🙏

Thanks for your plugin and help!

**Comment by plain-solutions-gmbh** [comment]
Good day
The Kirby Column Blocks plugin is no longer under development. If you have found a way to implement your request, you are welcome to submit a pull request.
Thank you for understanding
