### ISSUE TITLE
[K4] 4.0 Compatibility

### ISSUE THREAD

**Issue by afbora** [youngcut/kirby-column-blocks#7]
![screen-capture-1759-column-blocks - Mægazine-plugins test](https://github.com/youngcut/kirby-column-blocks/assets/3393422/903ece65-7766-4be1-941a-04f9fe45e45e)

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by plain-solutions-gmbh** [comment]
No longer supported.
