### ISSUE TITLE
Columns in panel take of 1 column in Kirby4

### ISSUE THREAD

**Issue by lexislav** [youngcut/kirby-column-blocks#8]
Hello,
Columns are working in Kirby 4, but not displaying correctly in the panel.
No matter what layout You choose (2 columns, 3 columns etc), columns display to 1 column width in panel. That makes it a bit hard to edit.
Could You please update this?
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/3668945a-3c0c-49b5-bbef-1b1fce40916b">

**Comment by plain-solutions-gmbh** [comment]
Thanks for reporting. It's fixed in [Version 1.1.0](https://github.com/plain-solutions-gmbh/kirby-column-blocks/releases/tag/1.1.0).
Please check it and tell me, if there's more issue left.

**Comment by lexislav** [comment]
Thanks for fast fix!

**Comment by plain-solutions-gmbh** [comment]
There is also a bit optimized version: 1.1.1.
It was a nice sunday-afternoon-bad-weather-activity. 😜
